### ISSUE TITLE
Some favicon are not downloaded

### ISSUE THREAD

**Issue by smutel** [navossoc/KeePass-Yet-Another-Favicon-Downloader#9] opened 2017-11-17 20:10 UTC
Hello,

Thank you for your plugin, it helps me very well.
I used it for all entries of my keepass database. I use Linux.
However some favicon was not downloaded.
Are you interested of a web site list where it does not work ?

Regards.

**Comment by navossoc** [comment] 2017-11-17 20:48
Sure!

Also, if you can provide more information it will be very helpful. 
Something like: what distribution are you using, keepass version, mono version and a few sites that are not working.

As soon as I get some free time, I'll try to reproduce the problem and I let you know.

**Comment by smutel** [comment] 2017-11-18 12:05
Ubuntu 17.10
Mono 4.6.2.7+dfsg-1ubuntu1 (provided by the distribution)
Keepass 2.36
Yet Another Favicon Downloader 1.1.1.0

Here is the list. Each time I tried it before putting it in the list. Some of them are working now.

_**Errors:**_
https://particulier.edf.fr/fr/accueil.html
https://forum.ubuntu-fr.org/index.php
https://accounts.google.com
https://my.kaspersky.com/
https://access.redhat.com/myaccount
https://www.banggood.com/login.html
https://www.carrefour.fr/personal-space
https://clients.cdiscount.com/Account/Login.html?
https://secure.fnac.com/account/register?LogonType=Standard&PageRedir=https%3A%2F%2Fsecure.fnac.com%2FAccount%2FProfil%2FDefault.aspx&PageAuth=X
https://www.lafoirfouille.fr/login
https://www.ubaldi.com/espace-perso/identification.php
https://www.materiel.net/pm/client/login.html
https://id.sonyentertainmentnetwork.com/signin/?client_id=55950157-ae9d-4b10-b0de-94dbef199f2c&scope=openid%2Ckamaji%3Aprivacy_control%2Ckamaji%3Aactivity_feed_get_feed_privacy%2Ckamaji%3Aactivity_feed_set_feed_privacy&state=e30%3D&redirect_uri=https%3A%2F%2Faccount.sonyentertainmentnetwork.com%2Foauth_security_check&response_type=code&prompt=login&ui=pr&noEVBlock=false&error=login_required&error_code=4165&error_description=User+is+not+authenticated#/signin?entry=%2Fsignin
https://westerndigital.secure.force.com/ind/?lang=fr_FR
https://www.cinemasgaumontpathe.com/mon-compte/identification.html
https://parlement-et-citoyens.fr/user
https://www.ruedelafete.com/login.html
https://www.lacentrale.fr/compte_ident.php
https://bioclinic.mesresultats.fr/login?came_from=https%3A%2F%2Fbioclinic.mesresultats.fr%2Fboard
https://assure.ameli.fr/PortailAS/appmanager/PortailAS/assure?_somtc=true
https://id.orange.fr/auth_user/bin/auth_user.cgi?service=sosh2&return_url=https://espaceclientv3.orange.fr/?sosh
http://fr.wikomobile.com/moncompte/engine.php?to=identification
https://www.1001pneus.fr/identification.html
https://www.g7.fr/login
https://maratp.ratp.fr/fr/user
https://www.jegeremacartenavigo.fr/connexion/connexion_ou_creation_compte
https://secure.viadeo.com/fr/signin
https://www.decathlon.fr/fr/loginPage
https://www.letanneur.com/fr/customer/account/login/
https://www.motoblouz.com/connexion.html
https://www.spartoo.com/securelogin.php?from=compte

**_Not found_**
https://sourceforge.net/auth/

Thanks.

**Comment by navossoc** [comment] 2017-11-18 12:31
I did a quick test on my Windows machine and most favicons are downloaded without issues.

Then I did another quick test with a Debian 9, KeePass 2.37 and Mono 4.6.2.7+dfsg-1 and I got the same results as you, except for the sourceforge.net which was downloaded successfully (they have a lot of mirrors, so may that is it).

Anyway, seems the issue is something specific to the linux environment...
I will look as soon as I can.

For now, just hold on there.

[]'s

**Comment by smutel** [comment] 2017-11-18 12:40
OK. Sounds good. Thanks.

2017-11-18 13:31 GMT+01:00 Rafael Cossovan <notifications@github.com>:

**Comment by navossoc** [comment] 2017-11-20 16:04
Seems most of the sites have errors related to SSL/TLS.

Mono uses it's own "certificate storage", not the system default.
I tried to synchronize both, but I didn't have much success.

I'm doing something wrong or that is not the exactly problem.
I'm still looking at it.

**Comment by navossoc** [comment] 2017-12-02 15:18
Hey @smutel I got some news...

The problem really is in the Mono runtime 4.6.x.

It seems to be fixed on Mono 4.8+.
https://sourceforge.net/p/keepass/discussion/329221/thread/b58633ef/

I have managed to download Mono 5.4.1.6 from the official mono repository.
Instructions here: http://www.mono-project.com/download/#download-lin-debian

You may also need to update your CA certificates (cert-sync):
Instructions here: http://www.mono-project.com/docs/faq/security/

I got the CA Certs from here:
https://curl.haxx.se/docs/caextract.html

This seems to fix the problem to me.

You can also wait the mono version from debian repo get updated, but I don't any idea when they will do that.

**Comment by smutel** [comment] 2017-12-02 15:24
Thank you.

Le 2 déc. 2017 4:18 PM, "Rafael Cossovan" <notifications@github.com> a
écrit :

**Closed** 2017-12-24 03:45 UTC
Labels: bug, mono, wontfix
